import React, {useEffect} from 'react'
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header/Header";
import Aos from "aos"
import "aos/dist/aos.css"

export default function Home() {
  useEffect(() => {
    Aos.init();
}, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.banner}>
          <div className={styles.overlay}></div>
          <div className={styles.textOverlay} data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
          <div className={styles.leftSide}>
              <h1 className={styles.mainTitle}>
             Welcome to sale weight training club</h1>
              <h2 className={styles.subTitle}>
              Train Hard, Lift Heavy, and Dominate Your Workouts at Cosmos Gym
              </h2>
              <div className={styles.ctaContainer}>
              <button className={styles.button15}><a>Join Now</a></button>
              <button className={styles.button15}><a>49£/month</a></button>
              <button className={styles.trial}><a>JOIN FREE TRIAL</a></button>
              </div>
            </div>
              <div className={styles.reviews}> 
                <img src="https://i8.amplience.net/i/jpl/screenshot-2023-04-13-at-140843-removebg-preview-ab4269db685f64c961a2735199ed7857" alt="reviews"/>
                </div>            
          </div>
        </div>
      </main>
    </>
  );
}
